//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ng.RozlZEE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JednostkaMiary
    {
        public JednostkaMiary()
        {
            this.SkladnikTaryfy = new HashSet<SkladnikTaryfy>();
        }
    
        public int Id { get; set; }
        public string Nazwa { get; set; }
    
        public virtual ICollection<SkladnikTaryfy> SkladnikTaryfy { get; set; }
    }
}
