//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ng.RozlZEE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licznik
    {
        public Licznik()
        {
            this.OdczytLicznika = new HashSet<OdczytLicznika>();
            this.SkladnikTaryfy = new HashSet<SkladnikTaryfy>();
        }
    
        public int Id { get; set; }
        public string NrFabryczny { get; set; }
        public Nullable<float> Mnozna { get; set; }
        public Nullable<int> TypLicznika { get; set; }
        public Nullable<float> ProcentStrat { get; set; }
        public bool Aktywny { get; set; }
        public Nullable<byte> Kolejnosc { get; set; }
        public string Opis { get; set; }
    
        public virtual Przylacze Przylacze { get; set; }
        public virtual ICollection<OdczytLicznika> OdczytLicznika { get; set; }
        public virtual ICollection<SkladnikTaryfy> SkladnikTaryfy { get; set; }
    }
}
