//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ng.RozlZEE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odbiorca
    {
        public Odbiorca()
        {
            this.Przylacze = new HashSet<Przylacze>();
        }
    
        public int Id { get; set; }
        public string NrOdbiorcy { get; set; }
        public string Konto { get; set; }
        public string KodPocztowy { get; set; }
        public string NrBudynku { get; set; }
        public Nullable<bool> Aktywny { get; set; }
        public string sNazwa { get; set; }
        public string sAdres { get; set; }
        public string sKod { get; set; }
        public string sMiasto { get; set; }
        public string sNIP { get; set; }
        public string sBank { get; set; }
        public string sNrRachunkuBankowego { get; set; }
    
        public virtual Miasto Miasto { get; set; }
        public virtual Obiekt Obiekt { get; set; }
        public virtual TypOdbiorcy TypOdbiorcy { get; set; }
        public virtual Ulica Ulica { get; set; }
        public virtual Zaklad Zaklad { get; set; }
        public virtual ICollection<Przylacze> Przylacze { get; set; }
    }
}
