//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ng.RozlZEE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przylacze
    {
        public Przylacze()
        {
            this.Licznik = new HashSet<Licznik>();
            this.MocZamowiona = new HashSet<MocZamowiona>();
            this.OsrodekKosztow = new HashSet<OsrodekKosztow>();
            this.Zuzycie = new HashSet<Zuzycie>();
        }
    
        public int Id { get; set; }
        public string Opis { get; set; }
        public Nullable<float> Mnozna { get; set; }
        public Nullable<float> TangensFiZamowione { get; set; }
        public Nullable<float> MocMinimalna { get; set; }
        public Nullable<float> MocUmowna { get; set; }
        public Nullable<float> MocZainstalowana { get; set; }
        public Nullable<int> TypTaryfaEBP { get; set; }
        public Nullable<bool> CzySumator { get; set; }
        public Nullable<bool> CzyStraty { get; set; }
        public Nullable<bool> Aktywne { get; set; }
    
        public virtual ICollection<Licznik> Licznik { get; set; }
        public virtual ICollection<MocZamowiona> MocZamowiona { get; set; }
        public virtual Odbiorca Odbiorca { get; set; }
        public virtual ICollection<OsrodekKosztow> OsrodekKosztow { get; set; }
        public virtual Taryfa Taryfa { get; set; }
        public virtual ICollection<Zuzycie> Zuzycie { get; set; }
    }
}
