//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ng.RozlZEE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rok
    {
        public Rok()
        {
            this.OsrodekKosztow = new HashSet<OsrodekKosztow>();
        }
    
        public int Id { get; set; }
        public int Numer { get; set; }
        public string MaskaKosztu { get; set; }
        public string DomyslnyStaly { get; set; }
        public string DomyslnyZmienny { get; set; }
    
        public virtual ICollection<OsrodekKosztow> OsrodekKosztow { get; set; }
    }
}
