//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ng.RozlZEE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RozlZEEEntities : DbContext
    {
        public RozlZEEEntities()
            : base("name=RozlZEEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asortyment> Asortyment { get; set; }
        public virtual DbSet<Cena> Cena { get; set; }
        public virtual DbSet<JednostkaMiary> JednostkaMiary { get; set; }
        public virtual DbSet<Licznik> Licznik { get; set; }
        public virtual DbSet<Miasto> Miasto { get; set; }
        public virtual DbSet<MocZamowiona> MocZamowiona { get; set; }
        public virtual DbSet<Obiekt> Obiekt { get; set; }
        public virtual DbSet<Odbiorca> Odbiorca { get; set; }
        public virtual DbSet<OdczytLicznika> OdczytLicznika { get; set; }
        public virtual DbSet<OsrodekKosztow> OsrodekKosztow { get; set; }
        public virtual DbSet<PozycjaZuzycia> PozycjaZuzycia { get; set; }
        public virtual DbSet<Przylacze> Przylacze { get; set; }
        public virtual DbSet<Rok> Rok { get; set; }
        public virtual DbSet<SkladnikTaryfy> SkladnikTaryfy { get; set; }
        public virtual DbSet<StawkaVAT> StawkaVAT { get; set; }
        public virtual DbSet<Taryfa> Taryfa { get; set; }
        public virtual DbSet<TypOdbiorcy> TypOdbiorcy { get; set; }
        public virtual DbSet<Ulica> Ulica { get; set; }
        public virtual DbSet<Zaklad> Zaklad { get; set; }
        public virtual DbSet<Zuzycie> Zuzycie { get; set; }
    }
}
