//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ng.RozlZEE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ulica
    {
        public Ulica()
        {
            this.Odbiorca = new HashSet<Odbiorca>();
        }
    
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public string Konto { get; set; }
    
        public virtual ICollection<Odbiorca> Odbiorca { get; set; }
    }
}
